# Generated by Django 6.0.1 on 2026-01-30 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('term', models.CharField(choices=[('early', '前期'), ('late', '後期'), ('full_year', '通年')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(help_text='Weight percentage (e.g. 30 for 30%)')),
                ('input_type', models.CharField(choices=[('score', '点数入力'), ('rate', '割合入力'), ('attendance', '出席入力'), ('none', '入力なし')], default='none', max_length=20)),
                ('is_leaf', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.evalnode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('root_only', '全体のみ')], default='root_only', max_length=20)),
                ('value', models.FloatField(default=60.0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='EvalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('attended', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('adjustment', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', '未入力'), ('completed', '入力済')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.evalnode')),
            ],
            options={
                'unique_together': {('user', 'node')},
            },
        ),
    ]
