# Generated by Django 6.0.1 on 2026-01-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalnode',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
