# Generated by Django 5.0.1 on 2026-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_id_alter_evalentry_id_alter_evalnode_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_classes',
            field=models.IntegerField(default=15, help_text='Total number of classes for this course'),
        ),
    ]
