# Generated by Django 5.0.1 on 2026-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_total_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_mask',
            field=models.BigIntegerField(default=0, help_text='Bitmask for attendance (1<<0 is 1st class)'),
        ),
    ]
