# Generated by Django 5.0.1 on 2026-02-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enrollment_year',
            field=models.IntegerField(blank=True, help_text='入学年（例: 2024）', null=True, verbose_name='入学年'),
        ),
    ]
