# Generated by Codex on 2026-02-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_target_enrollment_year(apps, schema_editor):
    Course = apps.get_model('api', 'Course')
    for course in Course.objects.filter(target_enrollment_year__isnull=True):
        course.target_enrollment_year = course.year
        course.save(update_fields=['target_enrollment_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_enrollment_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='attendance_mask',
        ),
        migrations.AddField(
            model_name='course',
            name='target_enrollment_year',
            field=models.IntegerField(
                blank=True,
                help_text='この科目を履修する学生の入学年（例: 2024年入学生向け）',
                null=True,
                verbose_name='対象入学年',
            ),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_mask', models.BigIntegerField(default=0, help_text='ビットマスク形式の出席記録', verbose_name='出席記録')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course', verbose_name='科目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '履修登録',
                'verbose_name_plural': '履修登録',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.RunPython(fill_target_enrollment_year, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='target_enrollment_year',
            field=models.IntegerField(
                help_text='この科目を履修する学生の入学年（例: 2024年入学生向け）',
                verbose_name='対象入学年',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'year', 'term', 'target_enrollment_year')},
        ),
    ]
