"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0af6rfj0u78#*x=339f@#h^(=k_%olf*m7-^-^rm+*3z5zgm#7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['133.125.84.34', 'localhost', '127.0.0.1', 'pai314.jp']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # Local apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _normalize_db_engine(engine: str) -> str:
    if engine in {'postgres', 'postgresql'}:
        return 'django.db.backends.postgresql'
    if engine in {'sqlite', 'sqlite3'}:
        return 'django.db.backends.sqlite3'
    return engine


def _database_from_url(url: str) -> dict:
    parsed = urlparse(url)
    engine = _normalize_db_engine(parsed.scheme)
    if engine == 'django.db.backends.sqlite3':
        # sqlite:////absolute/path.db or sqlite:///relative/path.db
        name = parsed.path or ''
        if name.startswith('/') and parsed.netloc:
            name = f'//{parsed.netloc}{name}'
        return {'ENGINE': engine, 'NAME': name}
    if engine != 'django.db.backends.postgresql':
        raise ValueError(f'Unsupported DATABASE_URL scheme: {parsed.scheme}')

    options = {k: v[-1] for k, v in parse_qs(parsed.query).items() if v}
    db = {
        'ENGINE': engine,
        'NAME': (parsed.path or '').lstrip('/'),
        'USER': parsed.username or '',
        'PASSWORD': parsed.password or '',
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }
    if options:
        db['OPTIONS'] = options
    return db


def _database_from_env() -> dict:
    engine = _normalize_db_engine(
        os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')
    )
    if engine == 'django.db.backends.sqlite3':
        name = os.environ.get('DB_NAME') or (BASE_DIR / 'db.sqlite3')
        return {'ENGINE': engine, 'NAME': name}

    return {
        'ENGINE': engine,
        'NAME': os.environ.get('DB_NAME')
        or os.environ.get('POSTGRES_DB')
        or '',
        'USER': os.environ.get('DB_USER')
        or os.environ.get('POSTGRES_USER')
        or '',
        'PASSWORD': os.environ.get('DB_PASSWORD')
        or os.environ.get('POSTGRES_PASSWORD')
        or '',
        'HOST': os.environ.get('DB_HOST')
        or os.environ.get('POSTGRES_HOST')
        or 'localhost',
        'PORT': os.environ.get('DB_PORT')
        or os.environ.get('POSTGRES_PORT')
        or '',
    }


DATABASE_URL = os.environ.get('DATABASE_URL')
DATABASES = {
    'default': _database_from_url(DATABASE_URL)
    if DATABASE_URL
    else _database_from_env()
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://133.125.84.34",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ],
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
